name: decise
description: Helping you make decisions.

version: 1.1.0+3

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^1.0.4
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  flutter_fortune_wheel: ^1.2.0
  uuid: ^3.0.6
  english_words: ^4.0.0
  gap: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.11
  hive_generator: ^1.1.3
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.2.2

flutter:
  uses-material-design: true

flutter_icons:
  # flutter pub run flutter_launcher_icons:main
  android: true
  ios: true
  image_path: 'assets/images/icon.png'
  adaptive_icon_background: '#BDBDBD'
  adaptive_icon_foreground: 'assets/images/foreground.png'

flutter_native_splash:
  # flutter pub run flutter_native_splash:create
  color: '#BDBDBD'
  image: 'assets/images/splash.png'
  color_dark: '#BDBDBD'
  image_dark: 'assets/images/splash.png'
  android: true
  ios: true
  web: false
  android12: true
